In [1]:
import numpy as np

In [2]:
x=np.matrix([[1],[1]])
A=np.matrix([[1,0],[0,5]])
y=np.matrix([[1],[-1]])
x

matrix([[1],
        [1]])

In [3]:
A

matrix([[1, 0],
        [0, 5]])

In [4]:
y

matrix([[ 1],
        [-1]])

In [5]:
norm_x = np.linalg.norm(x.T @ A @ x)
norm_y = np.linalg.norm(y.T @ A @ y)
ang = (x.T @ A @ y) / (np.sqrt(norm_x) * np.sqrt(norm_y))

In [6]:
ang 

matrix([[-0.66666667]])

In [7]:
np.arccos(ang)

matrix([[2.30052398]])